trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Backend
  displayName: 'Build .NET 6 Backend'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
      dotnet build --configuration Release
      dotnet test --configuration Release
    displayName: 'Build and Test .NET Backend'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'dotnet-backend'
      publishLocation: 'Container'

- job: Frontend
  displayName: 'Build Angular 16 Frontend'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true

  - script: |
      npm install
      npm run build --prod
    displayName: 'Install and Build Angular'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'angular-frontend'
      publishLocation: 'Container'
